# Generated by Django 4.2.1 on 2023-07-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=122)),
                ('middle_name', models.CharField(max_length=122)),
                ('last_name', models.CharField(max_length=122)),
                ('course', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('current_address', models.TextField()),
                ('password', models.CharField(max_length=122)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
